on:
  pull_request:
    branches: [main]

jobs:
  build-js-layer-deps:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Build chalice Layer - Prod
    container:
      image: "python:3.7"  #aca puede poner la imagen que deseas
    steps:
      - uses: actions/checkout@v2

      - run: |
          mkdir package
          cp package
          apt update -y && apt install zip -y
          zip -r model_deployment_package.zip package/
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Install dependencies
        run: |
         pip install -r api-serveless/requirements.txt
      - uses: actions/upload-artifact@v2
        with:
          name: boto3depens
          path: api-serveless/model_deployment_package.zip
  
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy DEV
    steps:
      - uses: actions/checkout@v2

      - name: Install Chalice
        run: |
          pip install chalice

      - name: Deploy with Chalice
        run: chalice deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Your Chalice App was deployed!
            Awesome :D
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
